data <- read.table("household.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
View(data)
data1<-subset(data,Date=="1/2/2007" | Date=="2/2/2007")
View(data1)
glob<-as.numeric(data1$Global_active_power )
data1$Date<-as.Date(data1$Date,format="%d/%m/%y")
datetym<-paste(data1$Date,data1$Time)
datetym<-as.POSIXct(datetym)
png("plot2.png", width=480, height=480)
plot(datetym, glob, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off() 
